name = "R Markdown"
grammar = "markdown"
path_suffixes = ["Rmd", "rmd", "qmd"]
line_comments = ["<!-- ", "# "]
tab_size = 4
soft_tabs = true
autoclose_before = "$@=,}])"
word_characters = []
collapsed_placeholder = "..."

brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
        "code_fence_content",
    ] },
]
